pipeline:
  name: feat23
  identifier: feat23
  projectIdentifier: dkushal_Playground
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fds
        identifier: fds
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
